### ISSUE TITLE
如果位置服务没有打开，会一直显示加载中

### ISSUE THREAD

**Issue by Flywan** [SmartDengg/RxWeather#4]
android版本： 4.4.4
这个我个人觉得可以改进一下

**Comment by heiwalebron** [comment]
请问点击foreast界面一直处于加载中怎么解决

**Comment by tedzyc** [comment]
rom版本cyanogenmod 6.0的系统，已打开位置服务，没有弹出请求位置的问询框。forecast卡在加载中
genymotion模拟器开启gps也不行
倒是酷派4.2的系统能跑  
是否程序的适应性不够强?
